"""
scripts/generate_indicator_catalog.py: the committed docs/indicator_catalog.json must not
drift from INDICATOR_SEED + GAP_PLAN. No database or filesystem write - pure data checks.
"""

import importlib.util
import json
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    "generate_indicator_catalog", Path(__file__).resolve().parent.parent / "scripts" / "generate_indicator_catalog.py")
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)

from indicators import INDICATOR_SEED

CATALOG_PATH = Path(__file__).resolve().parent.parent / "docs" / "indicator_catalog.json"


def test_catalog_has_one_row_per_seeded_indicator():
    rows = gen.build_catalog()
    assert {r["key"] for r in rows} == {d["key"] for d in INDICATOR_SEED}
    assert len(rows) == len(INDICATOR_SEED)


def test_every_row_carries_a_status_from_the_known_class_list():
    from importlib import import_module
    gaps = gen.gaps
    rows = gen.build_catalog()
    for r in rows:
        assert r["status"] in gaps.CLASS_ORDER, f"{r['key']}: unknown status {r['status']!r}"


def test_committed_catalog_file_matches_the_generator():
    assert CATALOG_PATH.exists(), "docs/indicator_catalog.json is missing - run scripts/generate_indicator_catalog.py"
    rendered = json.dumps(
        {
            "$comment": "Generated by scripts/generate_indicator_catalog.py - do not hand-edit. "
                         "Re-run it after changing indicators.py's INDICATOR_SEED or scripts/indicator_gaps.py's GAP_PLAN.",
            "indicator_count": len(INDICATOR_SEED),
            "status_meaning": gen.CLASS_MEANING,
            "axis_meaning": {
                "need": "Scores how much the company needs help (the problem side).",
                "readiness": "Scores how ready the company is to act on a pilot (the capability side). Never blended with need.",
                "both": "Scores on both axes independently.",
                "context": "Not scored (weight 0). Segment tag, trend context, or a computed passthrough.",
            },
            "tier_meaning": {
                "T1": "Structured register/API - deterministic, no interpretation needed.",
                "T2": "Scrape + extract - needs a crawler and/or LLM extraction over unstructured pages.",
                "T3": "Manual - first-contact interview, tier PHASE_MANUAL, not automatable by design.",
            },
            "indicators": gen.build_catalog(),
        },
        indent=2, ensure_ascii=False, sort_keys=False,
    ) + "\n"
    on_disk = CATALOG_PATH.read_text(encoding="utf-8")
    assert on_disk == rendered, "docs/indicator_catalog.json is stale - run: python scripts/generate_indicator_catalog.py"


def test_producer_file_hints_only_point_at_files_that_exist():
    root = Path(__file__).resolve().parent.parent
    for needle, path in gen.PRODUCER_FILE_HINTS:
        assert (root / path).exists(), f"PRODUCER_FILE_HINTS entry {needle!r} points at a missing file: {path}"
